"""
credential_deception.py
-----------------------

MIRAGE Credential Deception Engine.

Generates fake credentials and deceptive authentication artifacts
for controlled deception environments.

IMPORTANT:
All credentials generated by this module are synthetic decoys.
They must not be used as real production credentials.
"""

import json
import secrets
from pathlib import Path
from typing import Any, Dict


class CredentialDeception:
    """
    Generate synthetic credential-deception artifacts.
    """

    # ========================================================
    # Fake Password File
    # ========================================================

    @staticmethod
    def create_fake_password_file(
        filepath: str,
    ) -> str:
        """
        Create a JSON file containing synthetic credentials.
        """

        fake_passwords = {
            "admin": (
                "MIRAGE-Admin-"
                + secrets.token_urlsafe(12)
            ),
            "root": (
                "MIRAGE-Root-"
                + secrets.token_urlsafe(12)
            ),
            "db_admin": (
                "MIRAGE-DB-"
                + secrets.token_urlsafe(12)
            ),
            "service_account": (
                "Svc-"
                + secrets.token_urlsafe(20)
            ),
        }

        path = Path(filepath)

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with path.open(
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                fake_passwords,
                file,
                indent=2,
            )

        return str(path)

    # ========================================================
    # Fake Shadow File
    # ========================================================

    @staticmethod
    def create_fake_shadow_file(
        filepath: str,
    ) -> str:
        """
        Create a synthetic Linux shadow-style decoy.

        These are fake hashes and must never correspond
        to real authentication credentials.
        """

        shadow_content = (
            "root:$6$MIRAGE_FAKE_ROOT:19000:0:99999:7:::\n"
            "admin:$6$MIRAGE_FAKE_ADMIN:19000:0:99999:7:::\n"
            "service:$6$MIRAGE_FAKE_SERVICE:19000:0:99999:7:::\n"
        )

        path = Path(filepath)

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with path.open(
            "w",
            encoding="utf-8",
        ) as file:

            file.write(
                shadow_content
            )

        return str(path)

    # ========================================================
    # Fake Kerberos Ticket
    # ========================================================

    @staticmethod
    def create_kerberos_ticket(
        filepath: str,
    ) -> str:
        """
        Create a synthetic Kerberos-style ticket artifact.

        This is only a deception artifact and is not
        intended for real Kerberos authentication.
        """

        ticket_data = {
            "principal": "admin@MIRAGE.LOCAL",
            "realm": "MIRAGE.LOCAL",
            "ticket": (
                "MIRAGE-FAKE-TICKET-"
                + secrets.token_urlsafe(48)
            ),
            "key": secrets.token_hex(32),
            "synthetic": True,
        }

        path = Path(filepath)

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with path.open(
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                ticket_data,
                file,
                indent=2,
            )

        return str(path)

    # ========================================================
    # Persona-Specific Credentials
    # ========================================================

    @staticmethod
    def generate_persona_specific_credentials(
        attacker_profile: Dict[str, Any],
        poisoned: bool = False,
    ) -> Dict[str, Any]:
        """
        Generate synthetic credentials associated with
        an observed attacker persona.

        The profile is used only to produce a deterministic
        decoy username.
        """

        profile_string = str(
            sorted(attacker_profile.items())
        )

        profile_id = (
            abs(hash(profile_string))
            % 1000
        )

        return {
            "username": (
                f"admin_{profile_id}"
            ),
            "password": (
                "MIRAGE-DECOY-"
                + secrets.token_urlsafe(16)
            ),
            "honey_hash": poisoned,
            "synthetic": True,
        }

    # ========================================================
    # Database Credentials
    # ========================================================

    @staticmethod
    def generate_db_credentials(
        service: str,
        honey_hash: bool = False,
    ) -> Dict[str, Any]:
        """
        Generate synthetic database credentials.

        The service name identifies the decoy target.
        """

        safe_service = (
            service.strip()
            .lower()
            .replace(" ", "_")
        )

        return {
            "service": safe_service,
            "user": "db_admin",
            "password": (
                "MIRAGE-DB-DECOY-"
                + secrets.token_urlsafe(16)
            ),
            "honey_hash": honey_hash,
            "synthetic": True,
        }

    # ========================================================
    # Fake API Key
    # ========================================================

    @staticmethod
    def generate_fake_api_key(
        provider: str = "MIRAGE",
    ) -> str:
        """
        Generate a synthetic API key.
        """

        return (
            f"{provider.upper()}_DECOY_"
            + secrets.token_urlsafe(24)
        )

    # ========================================================
    # Fake Cloud Credentials
    # ========================================================

    @staticmethod
    def generate_cloud_credentials(
        provider: str,
    ) -> Dict[str, Any]:
        """
        Generate synthetic cloud-provider credentials.

        These values are intentionally non-functional.
        """

        provider = provider.lower().strip()

        if provider == "aws":

            return {
                "provider": "aws",
                "access_key_id": (
                    "MIRAGEDECOY"
                    + secrets.token_hex(8).upper()
                ),
                "secret_access_key": (
                    secrets.token_urlsafe(32)
                ),
                "synthetic": True,
            }

        if provider == "gcp":

            return {
                "provider": "gcp",
                "client_email": (
                    "mirage-decoy@"
                    "mirage.local"
                ),
                "private_key": (
                    "MIRAGE_FAKE_PRIVATE_KEY_"
                    + secrets.token_urlsafe(32)
                ),
                "synthetic": True,
            }

        if provider == "azure":

            return {
                "provider": "azure",
                "client_id": (
                    secrets.token_hex(16)
                ),
                "client_secret": (
                    secrets.token_urlsafe(32)
                ),
                "tenant_id": (
                    secrets.token_hex(16)
                ),
                "synthetic": True,
            }

        raise ValueError(
            f"Unsupported cloud provider: {provider}"
        )


# ============================================================
# Module-Level Helper Functions
# ============================================================

def generate_persona_specific_credentials(
    attacker_profile: dict,
    poisoned: bool = False,
):
    """
    Convenience wrapper around CredentialDeception.
    """

    return (
        CredentialDeception
        .generate_persona_specific_credentials(
            attacker_profile,
            poisoned,
        )
    )


def generate_db_credentials(
    service: str,
    honey_hash: bool = False,
):
    """
    Convenience wrapper around CredentialDeception.
    """

    return (
        CredentialDeception
        .generate_db_credentials(
            service,
            honey_hash,
        )
    )


def generate_fake_api_key(
    provider: str = "MIRAGE",
):
    """
    Convenience wrapper for fake API keys.
    """

    return (
        CredentialDeception
        .generate_fake_api_key(
            provider
        )
    )


def generate_cloud_credentials(
    provider: str,
):
    """
    Convenience wrapper for cloud credentials.
    """

    return (
        CredentialDeception
        .generate_cloud_credentials(
            provider
        )
    )